apiVersion: v1     
kind: Service
metadata:
  name: app
  labels:
    app: app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: app

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: appdeployment
spec:
  selector:
    matchLabels:
      app: app
  replicas: 2
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: michalazarovitz/midproj
        ports:
        - containerPort: 5000